language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew clean assemble check -Dpre-dex=false --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
